import { sqliteTable, text, integer, index, uniqueIndex, check } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
export const users=sqliteTable('users',{id:text().primaryKey(),email:text().notNull(),name:text().notNull(),role:text().notNull(),active:integer().notNull().default(1),createdAt:text().notNull()},t=>[uniqueIndex('users_email').on(t.email),check('valid_role',sql.raw("role in ('staff','head','deputy','dean','admin')"))]);
export const invites=sqliteTable('invites',{email:text().primaryKey(),role:text().notNull(),name:text().notNull(),active:integer().notNull().default(1)});
export const settings=sqliteTable('settings',{key:text().primaryKey(),value:text().notNull()});
export const categories=sqliteTable('categories',{name:text().primaryKey()});
export const branches=sqliteTable('branches',{name:text().primaryKey()});
export const locations=sqliteTable('locations',{name:text().primaryKey()});
export const groups=sqliteTable('asset_groups',{name:text().primaryKey(),description:text().notNull()});
export const imports=sqliteTable('imports',{id:text().primaryKey(),name:text().notNull(),hash:text().notNull(),objectKey:text().notNull(),rowCount:integer().notNull(),createdAt:text().notNull(),actor:text().notNull()},t=>[uniqueIndex('imports_hash').on(t.hash)]);
export const sources=sqliteTable('source_rows',{id:text().primaryKey(),sourceId:text().notNull(),sourceRow:text().notNull(),raw:text().notNull(),decision:text().notNull(),reason:text().notNull(),actor:text().notNull(),createdAt:text().notNull()},t=>[uniqueIndex('source_row_once').on(t.sourceId,t.sourceRow)]);
export const assets=sqliteTable('assets',{
id:text().primaryKey(),code:text().notNull(),name:text().notNull(),quantity:integer().notNull(),unitSatang:integer().notNull(),totalSatang:integer().notNull(),notes:text().notNull().default(''),
location:text().notNull().references(()=>locations.name),branch:text().notNull().references(()=>branches.name),category:text().notNull().references(()=>categories.name),groupName:text().notNull().references(()=>groups.name),
condition:text().notNull().default('normal'),lifecycle:text().notNull().default('active'),version:integer().notNull().default(1),parentId:text(),sourceId:text(),sourceRow:text(),receivedDate:text().notNull().default(''),lifeYears:integer().notNull().default(0),salvageSatang:integer().notNull().default(0),serial:text().notNull().default(''),brand:text().notNull().default(''),custodian:text().notNull().default(''),createdAt:text().notNull()
},t=>[uniqueIndex('asset_code_unique').on(t.code),index('asset_lifecycle_branch').on(t.lifecycle,t.branch),index('asset_parent').on(t.parentId),check('positive_quantity',sql.raw('quantity>0')),check('nonnegative_money',sql.raw('unitSatang>=0 and totalSatang>=0 and salvageSatang>=0 and salvageSatang<=totalSatang'))]);
export const operations=sqliteTable('operations',{id:text().primaryKey(),valid:integer().notNull(),actor:text().notNull(),createdAt:text().notNull()},t=>[check('operation_assertion',sql.raw('valid=1'))]);
export const audit=sqliteTable('audit',{id:text().primaryKey(),assetId:text(),actor:text().notNull(),actorName:text().notNull(),action:text().notNull(),before:text().notNull(),after:text().notNull(),reason:text().notNull(),createdAt:text().notNull()},t=>[index('audit_asset').on(t.assetId,t.createdAt)]);
export const requests=sqliteTable('requests',{id:text().primaryKey(),assetId:text().notNull().references(()=>assets.id),assetVersion:integer().notNull(),kind:text().notNull(),payload:text().notNull(),reason:text().notNull(),stage:integer().notNull().default(0),chain:text().notNull(),status:text().notNull().default('pending'),version:integer().notNull().default(1),actor:text().notNull(),createdAt:text().notNull()},t=>[index('request_status').on(t.status)]);
export const approvals=sqliteTable('approvals',{id:text().primaryKey(),requestId:text().notNull().references(()=>requests.id),stage:integer().notNull(),decision:text().notNull(),actor:text().notNull(),note:text().notNull(),createdAt:text().notNull()},t=>[uniqueIndex('approval_stage_once').on(t.requestId,t.stage)]);
export const stocktakes=sqliteTable('stocktakes',{id:text().primaryKey(),name:text().notNull(),year:integer().notNull(),status:text().notNull().default('open'),createdAt:text().notNull(),closedAt:text()});
export const stocktakeItems=sqliteTable('stocktake_items',{id:text().primaryKey(),roundId:text().notNull().references(()=>stocktakes.id),assetId:text().notNull().references(()=>assets.id),snapshot:text().notNull(),result:text().notNull().default('pending'),quantity:integer(),notes:text().notNull().default(''),actor:text(),checkedAt:text()},t=>[uniqueIndex('stocktake_asset_once').on(t.roundId,t.assetId)]);

